### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hmudassirs** [padreati/rapaio-jupyter-kernel#62]
D:\java\jupyter>java --version
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8-16)
OpenJDK 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

(.ijava) D:\java\jupyter>jupyter --version
Selected Jupyter core packages...
IPython          : 8.26.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.3
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.2.4
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 5.4.0
qtconsole        : 5.5.2
traitlets        : 5.14.3

(.ijava) D:\java\jupyter>java -jar ./rapaio-jupyter-kernel-2.0.0.jar -i -auto

(.ijava) D:\java\jupyter>

installing jar isn't working, OS WIN10

**Comment by padreati** [comment]
I will look over it. 

Which is the output of the installer command: `D:\java\jupyter>java -jar ./rapaio-jupyter-kernel-2.0.0.jar -i -auto` ?

**Comment by hmudassirs** [comment]
nothing appeared on the terminal.

**Comment by padreati** [comment]
Sorry for being late. I just get a windows host and I am able to reproduce. I will investigate the issue and push a new release with the solution soon.
