### ISSUE TITLE
Allow snapshots to be resolved (especially for local repo)

### ISSUE THREAD

**Issue by dsyer** [padreati/rapaio-jupyter-kernel#63]
It's quite common to use the Maven local repo for storing local artifacts in snapshot versions, so it's not very helpful that the dependency magic adds new repos with snapshots turned off. There should be an option to resolve snapshots from a custom reporitory.

I think this used to work (when I tested #49) so it may be a regression to do with the use of Mima.

**Comment by padreati** [comment]
Hi. This is true, the repositories were added with snapshots turned off. I fixed that, but some it remain a question. I fixed now by enabling snapshots on all repositories with update policy being `always`. Do you think it is useful in this way or it might be useful to allow total customization? A total customization would be to allow extra parameters to /add-repo such that one can enable snapshots it is desired and specify the update policy. What do you think?

**Comment by dsyer** [comment]
Parameterizing the magic would be the most flexible, but maybe it would help to use some conventions to choose the defaults? Eg a repo with “snapshot” in the name would be for snapshots; a file:// url would allow snapshots and releases.

I also think it should be possible to add the local repository by default. Its location must be available through a settings API in Mima? If not then just assume 
`${HOME}/.m2/repository`.

**Comment by padreati** [comment]
I implemented release/snapshot flags with options. I did not added by default the local repository. I am not sure if that is a good decision for remote notebooks.
