### ISSUE TITLE
Alter CLASSPATH when starting kernel

### ISSUE THREAD

**Issue by rgemulla** [padreati/rapaio-jupyter-kernel#73]
Is it possible to alter the class path before starting the kernel, thereby avoiding notebook imports via magic commands?

(This has been possible in ijava by setting environment variable IJAVA_CLASSPATH in kernel.json.)

**Comment by padreati** [comment]
Looking into adding something like this in kernel. I think I can do it by the end of the week.

**Comment by padreati** [comment]
I have created an environment variable `RJK_CLASSPATH` which follows a similar semantic. I hope it works in all cases (never tested on Windows, but it was implemented without OS dependent stuff). Additionally for the glob syntax I mostly used what Java already provides with some additional tricks. An example can be found in KERNEL.md from the git home.

**Comment by rgemulla** [comment]
Works flawlessly for me, thanks!
